# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: "**" 
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies for both projects
    - name: Restore dependencies for API
      run: dotnet restore
      working-directory: BerAuto_API
    
    - name: Restore dependencies for Frontend
      run: dotnet restore
      working-directory: BerAuto_Front

    # Build both projects
    - name: Build API
      run: dotnet build --no-restore
      working-directory: BerAuto_API
    
    - name: Build Frontend
      run: dotnet build --no-restore
      working-directory: BerAuto_Front

    # Run tests for API (assuming frontend doesn't have tests)
    - name: Test API
      run: dotnet test --no-build --verbosity normal
      working-directory: BerAuto_API

    # Optional: Publish the Blazor WebAssembly app
    - name: Publish Frontend
      run: dotnet publish -c Release -o release
      working-directory: BerAuto_Front

