name: .NET

on:
  push:
    branches: "**" 
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Cache NuGet packages to speed up restore
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Restore dependencies for API
      run: dotnet restore
      working-directory: BerAuto_API
    
    - name: Restore dependencies for Frontend
      run: dotnet restore
      working-directory: BerAuto_Front

    - name: Cache .NET build artifacts
      uses: actions/cache@v3
      with:
        path: |
          BerAuto_API/bin
          BerAuto_API/obj
          BerAuto_Front/bin
          BerAuto_Front/obj
        key: dotnet-build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          dotnet-build-${{ runner.os }}-

    - name: Build API
      run: dotnet build --no-restore
      working-directory: BerAuto_API
    
    - name: Build Frontend
      run: dotnet build --no-restore
      working-directory: BerAuto_Front

    - name: Test API
      run: dotnet test --no-build --verbosity normal
      working-directory: BerAuto_API

    - name: Publish Frontend
      run: dotnet publish -c Release -o release
      working-directory: BerAuto_Front

