name: .NET

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    # Cache NuGet packages to speed up restore
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    # Restore dependencies for the entire solution
    - name: Restore dependencies for Solution
      run: dotnet restore BerAuto.sln

    - name: Cache .NET build artifacts
      uses: actions/cache@v3
      with:
        path: |
          **/bin
          **/obj
        key: dotnet-build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          dotnet-build-${{ runner.os }}-

    # Build all projects in the solution
    - name: Build Solution
      run: dotnet build --no-restore BerAuto.sln

    # Test all projects in the solution
    - name: Test Solution
      run: dotnet test --no-build --verbosity normal BerAuto.sln
